model:
  user:
    max_name: 50
    max_email: 255
    min_pass: 6
    time_expire: 2

  micropost:
    max_size: 140
    pic_size: 5

helpers:
  user_helper:
    size: 80

view:
  user:
    _user:
      size: 50

    show_follow:
      size: 30

  microposts:
    post:
      size: 50

  shared:
    user_info:
      size: 50

uploader:
  pic_upload:
    limit: 400
